---
- name: "Fail if OS/Architecture is not supported"
  fail:
    msg: "Installing kubelet on {{ (ansible_os_family | lower) + '_' + (ansible_architecture | lower) }} is unsupported."
  when:
    - "(install_kubelet_packages | default({}))[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] is not defined"
    - "kubelet is defined"
  tags:
    - "kubelet"
- name: "Install kubelet"
  package:
    pkg: "{{ install_kubelet_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  when:
    - "kubelet is defined"
  tags:
    - "kubelet"
